# Generated by Django 5.1.3 on 2025-04-03 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='tags',
            field=models.ManyToManyField(related_name='folders', to='recipebox_app.tag'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', to='recipebox_app.ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='recipebox_app.tag'),
        ),
        migrations.AddField(
            model_name='recipelibrary',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipebox_app.folder'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='ingredients',
            field=models.ManyToManyField(related_name='shopping_lists', to='recipebox_app.ingredient'),
        ),
    ]
